resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- pvc.yaml
- config.yaml
- rbac.yaml
- secret.yaml
commonLabels:
  app: omni-repository-server
  owner: tommylike
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: omni-repository
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/omni/omni-repository-test
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/omni/omni-repository-test
  newTag: 8e057ede641116d8dafcc361fbe11db1a0b741ee
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
