---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: omni-repository-secret
  namespace: omni-repository
spec:
  name: omni-repository-secret
  keysMap:
    app_toml:
      path: secrets/data/infra-test/omni-repository
      key: app_toml