name = "omni-repository"
[server]
publicHttpPort = 8101
internalHttpPort = 8500
dataFolder = "./data/"
[log]
logFile = "./logs/info-{date}.log"
errFile = "./logs/error-{date}.log"
[repoManager]
[workManager]
threads = 10
syncInterval = 30
    [workManager.workers.imagePuller]
        maxRetry = 5
    [workManager.workers.imagerPusher]
        endpoint = "obs.ap-southeast-1.myhuaweicloud.com"
        ak = ""
        sk = ""
        bucket = "omni-images-test"
        partSize = 419430400
[persistentStore]
host = "192.168.1.193"
user = "root"
password = "rootpswd"
dbname = "omni_repository"
port = "3306"
[mq]
kafka_brokers = ""