name = "OmniRepository"
timezone = "PRC"
httpPort = 8080
serverName = "localhost:8080"
[log]
logFile = "/app/logs/run-application-{date}.log"
errFile = "/app/logs/run-error-{date}.log"

[manager]
dataFolder = "/app/data/"
uploadToken = "316462d0c029ba707ad1"
callBackUrl = "http://127.0.0.1:8080/api/v3/baseImages/repoCallback/%d?status=%s"

[database]
dbHost = "192.168.1.193"
dbUser = "root"
dbPswd = "rootpswd"
dbName = "omni_repository"
dbPort = "3306"
[redis]
address = "192.168.1.193"
port = "6379"
password = "58243586"
dbIndex = 0 